export const productTypes = {

  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",

  CREATE_PRODUCT: "CREATE_PRODUCT",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  DELETE_PRODUCT: "DELETE_PRODUCT",

  DELETE_MUL_PRODUCT: "DELETE_MUL_PRODUCT",
};
